### ISSUE TITLE
Feature doubt and request?

### ISSUE THREAD

**Issue by sheminasalam** [pawelka/sofarsolar_esp_rs485_logger#9]
Does this give the following parameters?

today_generation
today_exported
today_purchase
today_consumption

**Comment by mgrom** [comment]
From what I've seen there is:
today_generation

Three others are not implemented

**Comment by pawelka** [comment]
SofarSolar inverter doesn't have information about energy consumption, you need additional hardware next to your energy meter to measure energy consumption and return from/to grid and having those information and energy generated by inverter you can calculate all above in HomeAssistant or other home automation software.

There is no way to add all those parameters, because there are missing data (hardware limitation and different purpose).

**Comment by sheminasalam** [comment]
The system already measures current and voltage from which we should be able to calculate power, apparent power , real power and powerfactor. I have seen this library which has implemented such a system with esp32.

https://github.com/Savjee/EmonLib-esp32

EmonLib.cpp file explains the process of calculation and also I found a video in youtube with may also be related.

https://youtu.be/PSzkaSy5lHY

I hope this could be useful.
